# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\patcher_Gnosia_PC_official\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 104)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(830, 10, 81, 31))
        self.pushButton_browse.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setGeometry(QtCore.QRect(420, 60, 61, 31))
        self.pushButton_process.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.pushButton_process.setObjectName("pushButton_process")
        self.lineEdit_gamePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gamePath.setGeometry(QtCore.QRect(10, 10, 811, 31))
        self.lineEdit_gamePath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_gamePath.setObjectName("lineEdit_gamePath")
        self.label_stateProcess = QtWidgets.QLabel(self.centralwidget)
        self.label_stateProcess.setGeometry(QtCore.QRect(500, 60, 211, 31))
        self.label_stateProcess.setObjectName("label_stateProcess")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Team Mirai - GNOSIA patcheur automatique"))
        self.pushButton_browse.setText(_translate("MainWindow", "rechercher"))
        self.pushButton_process.setText(_translate("MainWindow", "Patcher"))
        self.label_stateProcess.setText(_translate("MainWindow", "text current state patch"))
import ressource_rc
